name: Infection
version: 0.1
main: com.impress.Infection.Infection
description: Infection gamemode
author: 1mpre55
softdepend: [TagAPI, DisguiseCraft]
commands:
  infection:
    description: Main command.
    usage: /<command> <action> [args...]
    aliases:
    - inf
permissions:
  infection.*:
    children:
      infection.something: true
    description: Gives all Infection permissions
    default: false