name: Infection
version: 0.1
main: com.impress.Infection.Infection
description: Infection gamemode
author: 1mpre55
softdepend: [TagAPI, DisguiseCraft]
commands:
  infection:
    description: Main command.
    usage: /<command> <action> [args...]
    aliases:
    - inf
  infjoin:
  	description: Infection's join game command. Equivalent to /inf join
    usage: /<command> [game] [team]
    aliases:
    - join
  infleave:
  	description: Infection's leave game command. Equivalent to /inf leave
    usage: /<command>
    aliases:
    - leave
  infchangeteam:
  	description: Infection's change team command. Equivalent to /inf changeteam
    usage: /<command> [team]
    aliases:
    - changeteam
  infadmin:
  	description: Infection's administrative command. Equivalent to /inf admin
    usage: /<command> [args...]
    aliases:
    - admin
permissions:
  infection.*:
    children:
      infection.something: true
    description: Gives all Infection permissions
    default: false
  infection.join
  	default: true
    description: Allows player to join any game
  infection.joinafterstart:
    description: Allows player to join any game after it started
  infection.jointeam:
    description: Allows player to choose what team to join in any game
  infection.changeteam:
    description: Allows player to change what team they are on (without re-joining) in any game
  infection.ignore.teambalance:
    description: Ignores team balance when joining or changing teams in any game
  infection.kits:
    description: Allows player to receive any kit